### PR TITLE
fixed transparency

### PR DESCRIPTION
**Pull request by vikbez**

### CODE REVIEW

**Comment by vikbez** [comment]
Should it be done this way ?

**Comment by vikbez** [comment]
No, still some problems:

http://grab.by/S1Hg

**Comment by vikbez** [comment]
seems to work ~ok

**Comment by ienaga** [comment]
@vikbez 

Thank you! Pull Requests!!!!!!!

However , "blend mode " did not work...

I have received a very big hint .

thank you very very much!

**Comment by vikbez** [comment]
Glad it helped !
Thanks !
(you should add a donate button 👍 )

**Pull request closed without merging**
