### PR TITLE
Add userscript

### PR DESCRIPTION
**Pull request by sjehuda**
This program sets instances for every flash object on page and will play it upon click on Play ⚡.

See https://openuserjs.org/scripts/sjehuda/Flash_Player

### CODE REVIEW

**Comment by ienaga** [comment]
@sjehuda 

Hello, 
Sorry for the late reply.

I looked at the service details, but did not fully understand, so I would like to ask you a question.
What effect/help would merging this PR have on the service you produced?

**Comment by sjehuda** [comment]
This is a browser extension, in a form of Userscript.

To install it, one needs to have a userscript manager (Greasemonkey,
Violentmonkey, Tampermonkey etc.)

This userscript let's people to utilize swf2js on any web page they
visit with a click, provided the page contains SWF files.

It is a small complement to the project.

**Comment by ROBERT-MCDOWELL** [comment]
@sjehuda 
but swf2js does not support the whole AS2/AS3 API like RTMP right?

**Comment by sjehuda** [comment]
On Tue, 11 Jul 2023 05:00:54 -0700
ROBERT MCDOWELL ***@***.***> wrote:

> @sjehuda 
> but swf2js does not support the whole AS2/AS3 API like RTMP right?
> 

I don't know.

And it doesn't matter.

An swf2js userscript is better than nothing.

**Comment by sjehuda** [comment]
On Tue, 11 Jul 2023 06:13:22 -0700
ROBERT MCDOWELL ***@***.***> wrote:

> I think ruffle is much better today...
> 

It might.

Yet, I think, swf2js is the only software that plays SWF file *and* is
completely written in JS, so unlike ruffle, no web assembly is needed.

I'm intending to write a userscript for ruffle too.

**Comment by ienaga** [comment]
@ROBERT-MCDOWELL @sjehuda 

Thanks for your input.
I am making this swf2js to run AS1 and AS2.
(AS3 is sold as a paid version).

Ruffle is a great library.
swf2js is not sponsored like ruffle, so I maintain it in my free time.

I know how to get AS1 and AS2 to work, but I am usually a salaried worker so it is difficult to make time for development.

**Comment by sjehuda** [comment]
> I know how to get AS1 and AS2 to work, but I am usually a salaried
> worker so it is difficult to make time for development.
> 

I know how difficult this is.

I have quit my day-job, to work on my own projects, and I also rejected
a very big and rare offer from the government while I was working on my
own projects.

**Comment by ROBERT-MCDOWELL** [comment]
@ienaga 
I was long time ago in your situation until I decided to use the rest of my life time to work for my own projects with of course much less money and I can tell you 26 years later I don't regret!  :D

@sjehuda
I'm sure it was the right choice for you ;)

**Pull request merged**
